// Generated by Haxe 4.3.0-rc.1+
#ifndef INCLUDED_pixelimage_iter_IntIterStart
#define INCLUDED_pixelimage_iter_IntIterStart

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_STACK_FRAME(_hx_pos_d512ee84cfff1ee1_9_new)
HX_DECLARE_CLASS2(pixelimage,iter,IntIterStart)

namespace pixelimage{
namespace iter{


class HXCPP_CLASS_ATTRIBUTES IntIterStart_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef IntIterStart_obj OBJ_;
		IntIterStart_obj();

	public:
		enum { _hx_ClassId = 0x6821d4ac };

		void __construct(int min_,int max_);
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="pixelimage.iter.IntIterStart")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,false,"pixelimage.iter.IntIterStart"); }

		inline static ::hx::ObjectPtr< IntIterStart_obj > __new(int min_,int max_) {
			::hx::ObjectPtr< IntIterStart_obj > __this = new IntIterStart_obj();
			__this->__construct(min_,max_);
			return __this;
		}

		inline static ::hx::ObjectPtr< IntIterStart_obj > __alloc(::hx::Ctx *_hx_ctx,int min_,int max_) {
			IntIterStart_obj *__this = (IntIterStart_obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(IntIterStart_obj), false, "pixelimage.iter.IntIterStart"));
			*(void **)__this = IntIterStart_obj::_hx_vtable;
{
            	HX_STACKFRAME(&_hx_pos_d512ee84cfff1ee1_9_new)
HXLINE(  10)		( (::pixelimage::iter::IntIterStart)(__this) )->start = min_;
HXLINE(  11)		( (::pixelimage::iter::IntIterStart)(__this) )->max = max_;
            	}
		
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~IntIterStart_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		::hx::Val __SetField(const ::String &inString,const ::hx::Val &inValue, ::hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("IntIterStart",5b,31,79,66); }

		int start;
		int max;
};

} // end namespace pixelimage
} // end namespace iter

#endif /* INCLUDED_pixelimage_iter_IntIterStart */ 
