// Generated by Haxe 4.3.0-rc.1+
#include <hxcpp.h>

#ifndef INCLUDED_haxe_zip_FlushMode
#include <haxe/zip/FlushMode.h>
#endif
#ifndef INCLUDED_haxe_io_Error
#include <haxe/io/Error.h>
#endif
#ifndef INCLUDED_haxe_io_Encoding
#include <haxe/io/Encoding.h>
#endif
#ifndef INCLUDED_format_png_Chunk
#include <format/png/Chunk.h>
#endif
#ifndef INCLUDED_format_png_Color
#include <format/png/Color.h>
#endif
#ifndef INCLUDED_pixelimage__Endian_Endian_Fields_
#include <pixelimage/_Endian/Endian_Fields_.h>
#endif
#ifndef INCLUDED_justPath__CurveMath_CurveMath_Fields_
#include <justPath/_CurveMath/CurveMath_Fields_.h>
#endif
#ifndef INCLUDED_haxe_xml_Parser
#include <haxe/xml/Parser.h>
#endif
#ifndef INCLUDED_haxe_Log
#include <haxe/Log.h>
#endif
#ifndef INCLUDED_Xml
#include <Xml.h>
#endif
#ifndef INCLUDED_vision_ds_Point2D
#include <vision/ds/Point2D.h>
#endif
#ifndef INCLUDED_vision_ds_Line2D
#include <vision/ds/Line2D.h>
#endif
#ifndef INCLUDED_sys_io_FileOutput
#include <sys/io/FileOutput.h>
#endif
#ifndef INCLUDED_sys_io_File
#include <sys/io/File.h>
#endif
#ifndef INCLUDED_pixelimage_samples_pixelimage_format__Grid_Grid_Fields_
#include <pixelimage_samples/pixelimage_format/_Grid/Grid_Fields_.h>
#endif
#ifndef INCLUDED_pixelimage_samples_pixelimage_format_Grid
#include <pixelimage_samples/pixelimage_format/Grid.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_shape_VePathElementShape
#include <pixelimage/triangleGML/shape/VePathElementShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_shape_TriangleShape
#include <pixelimage/triangleGML/shape/TriangleShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_shape_Star6Shape
#include <pixelimage/triangleGML/shape/Star6Shape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_shape_SquareShape
#include <pixelimage/triangleGML/shape/SquareShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_shape_RectangleShape
#include <pixelimage/triangleGML/shape/RectangleShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_shape_QuadrilateralShape
#include <pixelimage/triangleGML/shape/QuadrilateralShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_shape_PathElementShape
#include <pixelimage/triangleGML/shape/PathElementShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_shape_EllipseShape
#include <pixelimage/triangleGML/shape/EllipseShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_shape_CircleShape
#include <pixelimage/triangleGML/shape/CircleShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_shape_ArcShape
#include <pixelimage/triangleGML/shape/ArcShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_patternShape_SquarePattern
#include <pixelimage/triangleGML/patternShape/SquarePattern.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_patternShape_RectanglePattern
#include <pixelimage/triangleGML/patternShape/RectanglePattern.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_patternShape_QuadrilateralPattern
#include <pixelimage/triangleGML/patternShape/QuadrilateralPattern.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_patternShape_PathElementPattern
#include <pixelimage/triangleGML/patternShape/PathElementPattern.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_patternShape_EllipsePattern
#include <pixelimage/triangleGML/patternShape/EllipsePattern.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_patternShape_CirclePattern
#include <pixelimage/triangleGML/patternShape/CirclePattern.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_patternShape_ArcPattern
#include <pixelimage/triangleGML/patternShape/ArcPattern.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_patternContour_TrianglePattern
#include <pixelimage/triangleGML/patternContour/TrianglePattern.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_patternContour_QuadPattern
#include <pixelimage/triangleGML/patternContour/QuadPattern.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_patternContour_LinePattern
#include <pixelimage/triangleGML/patternContour/LinePattern.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_patternContour_CubicCurvePattern
#include <pixelimage/triangleGML/patternContour/CubicCurvePattern.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_gradientContour_PolyLineGradient
#include <pixelimage/triangleGML/gradientContour/PolyLineGradient.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_gradientContour_LineGradient
#include <pixelimage/triangleGML/gradientContour/LineGradient.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_gradient_TriangleGradient
#include <pixelimage/triangleGML/gradient/TriangleGradient.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_gradient_QuadGradient
#include <pixelimage/triangleGML/gradient/QuadGradient.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_gradient_PathElementThickGradient
#include <pixelimage/triangleGML/gradient/PathElementThickGradient.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_gradient_EllipseRadialGradient
#include <pixelimage/triangleGML/gradient/EllipseRadialGradient.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_gradient_ArrowThickGradient
#include <pixelimage/triangleGML/gradient/ArrowThickGradient.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_coreShape__TriangleGML_TriangleGML_Fields_
#include <pixelimage/triangleGML/coreShape/_TriangleGML/TriangleGML_Fields_.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_coreShape_TriangleGML
#include <pixelimage/triangleGML/coreShape/TriangleGML.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_coreShape_PatternStroke
#include <pixelimage/triangleGML/coreShape/PatternStroke.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_coreShape_PatternShape
#include <pixelimage/triangleGML/coreShape/PatternShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_coreShape_BasicGradient
#include <pixelimage/triangleGML/coreShape/BasicGradient.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_contour_TriangleSoftShape
#include <pixelimage/triangleGML/contour/TriangleSoftShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_contour_ThruCurveShape
#include <pixelimage/triangleGML/contour/ThruCurveShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_contour_SoftEllipseShape
#include <pixelimage/triangleGML/contour/SoftEllipseShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_contour_QuintShape
#include <pixelimage/triangleGML/contour/QuintShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_contour_QuadSoftShape
#include <pixelimage/triangleGML/contour/QuadSoftShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_contour_QuadShape
#include <pixelimage/triangleGML/contour/QuadShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_contour_QuadCurveShape
#include <pixelimage/triangleGML/contour/QuadCurveShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_contour_PolyLineShape
#include <pixelimage/triangleGML/contour/PolyLineShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_contour_LineShape
#include <pixelimage/triangleGML/contour/LineShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_contour_LineGridShape
#include <pixelimage/triangleGML/contour/LineGridShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_contour_CubicCurveShape
#include <pixelimage/triangleGML/contour/CubicCurveShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_coreShape_FillShape
#include <pixelimage/triangleGML/coreShape/FillShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_contour_ArrowShape
#include <pixelimage/triangleGML/contour/ArrowShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_coreShape_BasicShape
#include <pixelimage/triangleGML/coreShape/BasicShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_coreShape_GroupShape
#include <pixelimage/triangleGML/coreShape/GroupShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_coreShape_ShapeInterface
#include <pixelimage/triangleGML/coreShape/ShapeInterface.h>
#endif
#ifndef INCLUDED_pixelimage_pixel__TwoGrad_TwoGrad_
#include <pixelimage/pixel/_TwoGrad/TwoGrad_.h>
#endif
#ifndef INCLUDED_pixelimage_iter_IntIterStart
#include <pixelimage/iter/IntIterStart.h>
#endif
#ifndef INCLUDED_pixelimage_draw_DrawTileHelper
#include <pixelimage/draw/DrawTileHelper.h>
#endif
#ifndef INCLUDED_pixelimage_draw_DrawShapeHelper
#include <pixelimage/draw/DrawShapeHelper.h>
#endif
#ifndef INCLUDED_pixelimage_algo_HitTriArray
#include <pixelimage/algo/HitTriArray.h>
#endif
#ifndef INCLUDED_pixelimage_algo_HitTri
#include <pixelimage/algo/HitTri.h>
#endif
#ifndef INCLUDED_pixelimage_algo_HitQuad
#include <pixelimage/algo/HitQuad.h>
#endif
#ifndef INCLUDED_pixelimage_algo_IhitObj
#include <pixelimage/algo/IhitObj.h>
#endif
#ifndef INCLUDED_pixelimage__Pixelimage_Pixelimage_Impl_
#include <pixelimage/_Pixelimage/Pixelimage_Impl_.h>
#endif
#ifndef INCLUDED_pixelimage_ImageStruct
#include <pixelimage/ImageStruct.h>
#endif
#ifndef INCLUDED_justPath_SvgLinePath
#include <justPath/SvgLinePath.h>
#endif
#ifndef INCLUDED_justPath_StoreF6
#include <justPath/StoreF6.h>
#endif
#ifndef INCLUDED_justPath_ILinePathContext
#include <justPath/ILinePathContext.h>
#endif
#ifndef INCLUDED_justPath_EllipseArc
#include <justPath/EllipseArc.h>
#endif
#ifndef INCLUDED_haxe_zip_Compress
#include <haxe/zip/Compress.h>
#endif
#ifndef INCLUDED_haxe_xml_Printer
#include <haxe/xml/Printer.h>
#endif
#ifndef INCLUDED_haxe_xml_XmlParserException
#include <haxe/xml/XmlParserException.h>
#endif
#ifndef INCLUDED_haxe_iterators_ArrayIterator
#include <haxe/iterators/ArrayIterator.h>
#endif
#ifndef INCLUDED_haxe_io_Path
#include <haxe/io/Path.h>
#endif
#ifndef INCLUDED_haxe_io_BytesOutput
#include <haxe/io/BytesOutput.h>
#endif
#ifndef INCLUDED_haxe_io_Output
#include <haxe/io/Output.h>
#endif
#ifndef INCLUDED_haxe_io_BytesBuffer
#include <haxe/io/BytesBuffer.h>
#endif
#ifndef INCLUDED_haxe_io_Bytes
#include <haxe/io/Bytes.h>
#endif
#ifndef INCLUDED_haxe_io_ArrayBufferViewImpl
#include <haxe/io/ArrayBufferViewImpl.h>
#endif
#ifndef INCLUDED_haxe_exceptions_NotImplementedException
#include <haxe/exceptions/NotImplementedException.h>
#endif
#ifndef INCLUDED_haxe_exceptions_PosException
#include <haxe/exceptions/PosException.h>
#endif
#ifndef INCLUDED_haxe_ds_StringMap
#include <haxe/ds/StringMap.h>
#endif
#ifndef INCLUDED_haxe_ds__List_ListNode
#include <haxe/ds/_List/ListNode.h>
#endif
#ifndef INCLUDED_haxe_ds_List
#include <haxe/ds/List.h>
#endif
#ifndef INCLUDED_haxe_ValueException
#include <haxe/ValueException.h>
#endif
#ifndef INCLUDED_haxe_NativeStackTrace
#include <haxe/NativeStackTrace.h>
#endif
#ifndef INCLUDED_haxe_Exception
#include <haxe/Exception.h>
#endif
#ifndef INCLUDED_haxe_IMap
#include <haxe/IMap.h>
#endif
#ifndef INCLUDED_format_tools_Deflate
#include <format/tools/Deflate.h>
#endif
#ifndef INCLUDED_format_png_Writer
#include <format/png/Writer.h>
#endif
#ifndef INCLUDED__Xml_XmlType_Impl_
#include <_Xml/XmlType_Impl_.h>
#endif
#ifndef INCLUDED_Type
#include <Type.h>
#endif
#ifndef INCLUDED_Sys
#include <Sys.h>
#endif
#ifndef INCLUDED_StringTools
#include <StringTools.h>
#endif
#ifndef INCLUDED_StringBuf
#include <StringBuf.h>
#endif
#ifndef INCLUDED_Std
#include <Std.h>
#endif
#ifndef INCLUDED_Reflect
#include <Reflect.h>
#endif
#ifndef INCLUDED_EReg
#include <EReg.h>
#endif

void __files__boot();

void __boot_all()
{
__files__boot();
::hx::RegisterResources( ::hx::GetResources() );
::haxe::zip::FlushMode_obj::__register();
::haxe::io::Error_obj::__register();
::haxe::io::Encoding_obj::__register();
::format::png::Chunk_obj::__register();
::format::png::Color_obj::__register();
::pixelimage::_Endian::Endian_Fields__obj::__register();
::justPath::_CurveMath::CurveMath_Fields__obj::__register();
::haxe::xml::Parser_obj::__register();
::haxe::Log_obj::__register();
::Xml_obj::__register();
::vision::ds::Point2D_obj::__register();
::vision::ds::Line2D_obj::__register();
::sys::io::FileOutput_obj::__register();
::sys::io::File_obj::__register();
::pixelimage_samples::pixelimage_format::_Grid::Grid_Fields__obj::__register();
::pixelimage_samples::pixelimage_format::Grid_obj::__register();
::pixelimage::triangleGML::shape::VePathElementShape_obj::__register();
::pixelimage::triangleGML::shape::TriangleShape_obj::__register();
::pixelimage::triangleGML::shape::Star6Shape_obj::__register();
::pixelimage::triangleGML::shape::SquareShape_obj::__register();
::pixelimage::triangleGML::shape::RectangleShape_obj::__register();
::pixelimage::triangleGML::shape::QuadrilateralShape_obj::__register();
::pixelimage::triangleGML::shape::PathElementShape_obj::__register();
::pixelimage::triangleGML::shape::EllipseShape_obj::__register();
::pixelimage::triangleGML::shape::CircleShape_obj::__register();
::pixelimage::triangleGML::shape::ArcShape_obj::__register();
::pixelimage::triangleGML::patternShape::SquarePattern_obj::__register();
::pixelimage::triangleGML::patternShape::RectanglePattern_obj::__register();
::pixelimage::triangleGML::patternShape::QuadrilateralPattern_obj::__register();
::pixelimage::triangleGML::patternShape::PathElementPattern_obj::__register();
::pixelimage::triangleGML::patternShape::EllipsePattern_obj::__register();
::pixelimage::triangleGML::patternShape::CirclePattern_obj::__register();
::pixelimage::triangleGML::patternShape::ArcPattern_obj::__register();
::pixelimage::triangleGML::patternContour::TrianglePattern_obj::__register();
::pixelimage::triangleGML::patternContour::QuadPattern_obj::__register();
::pixelimage::triangleGML::patternContour::LinePattern_obj::__register();
::pixelimage::triangleGML::patternContour::CubicCurvePattern_obj::__register();
::pixelimage::triangleGML::gradientContour::PolyLineGradient_obj::__register();
::pixelimage::triangleGML::gradientContour::LineGradient_obj::__register();
::pixelimage::triangleGML::gradient::TriangleGradient_obj::__register();
::pixelimage::triangleGML::gradient::QuadGradient_obj::__register();
::pixelimage::triangleGML::gradient::PathElementThickGradient_obj::__register();
::pixelimage::triangleGML::gradient::EllipseRadialGradient_obj::__register();
::pixelimage::triangleGML::gradient::ArrowThickGradient_obj::__register();
::pixelimage::triangleGML::coreShape::_TriangleGML::TriangleGML_Fields__obj::__register();
::pixelimage::triangleGML::coreShape::TriangleGML_obj::__register();
::pixelimage::triangleGML::coreShape::PatternStroke_obj::__register();
::pixelimage::triangleGML::coreShape::PatternShape_obj::__register();
::pixelimage::triangleGML::coreShape::BasicGradient_obj::__register();
::pixelimage::triangleGML::contour::TriangleSoftShape_obj::__register();
::pixelimage::triangleGML::contour::ThruCurveShape_obj::__register();
::pixelimage::triangleGML::contour::SoftEllipseShape_obj::__register();
::pixelimage::triangleGML::contour::QuintShape_obj::__register();
::pixelimage::triangleGML::contour::QuadSoftShape_obj::__register();
::pixelimage::triangleGML::contour::QuadShape_obj::__register();
::pixelimage::triangleGML::contour::QuadCurveShape_obj::__register();
::pixelimage::triangleGML::contour::PolyLineShape_obj::__register();
::pixelimage::triangleGML::contour::LineShape_obj::__register();
::pixelimage::triangleGML::contour::LineGridShape_obj::__register();
::pixelimage::triangleGML::contour::CubicCurveShape_obj::__register();
::pixelimage::triangleGML::coreShape::FillShape_obj::__register();
::pixelimage::triangleGML::contour::ArrowShape_obj::__register();
::pixelimage::triangleGML::coreShape::BasicShape_obj::__register();
::pixelimage::triangleGML::coreShape::GroupShape_obj::__register();
::pixelimage::triangleGML::coreShape::ShapeInterface_obj::__register();
::pixelimage::pixel::_TwoGrad::TwoGrad__obj::__register();
::pixelimage::iter::IntIterStart_obj::__register();
::pixelimage::draw::DrawTileHelper_obj::__register();
::pixelimage::draw::DrawShapeHelper_obj::__register();
::pixelimage::algo::HitTriArray_obj::__register();
::pixelimage::algo::HitTri_obj::__register();
::pixelimage::algo::HitQuad_obj::__register();
::pixelimage::algo::IhitObj_obj::__register();
::pixelimage::_Pixelimage::Pixelimage_Impl__obj::__register();
::pixelimage::ImageStruct_obj::__register();
::justPath::SvgLinePath_obj::__register();
::justPath::StoreF6_obj::__register();
::justPath::ILinePathContext_obj::__register();
::justPath::EllipseArc_obj::__register();
::haxe::zip::Compress_obj::__register();
::haxe::xml::Printer_obj::__register();
::haxe::xml::XmlParserException_obj::__register();
::haxe::iterators::ArrayIterator_obj::__register();
::haxe::io::Path_obj::__register();
::haxe::io::BytesOutput_obj::__register();
::haxe::io::Output_obj::__register();
::haxe::io::BytesBuffer_obj::__register();
::haxe::io::Bytes_obj::__register();
::haxe::io::ArrayBufferViewImpl_obj::__register();
::haxe::exceptions::NotImplementedException_obj::__register();
::haxe::exceptions::PosException_obj::__register();
::haxe::ds::StringMap_obj::__register();
::haxe::ds::_List::ListNode_obj::__register();
::haxe::ds::List_obj::__register();
::haxe::ValueException_obj::__register();
::haxe::NativeStackTrace_obj::__register();
::haxe::Exception_obj::__register();
::haxe::IMap_obj::__register();
::format::tools::Deflate_obj::__register();
::format::png::Writer_obj::__register();
::_Xml::XmlType_Impl__obj::__register();
::Type_obj::__register();
::Sys_obj::__register();
::StringTools_obj::__register();
::StringBuf_obj::__register();
::Std_obj::__register();
::Reflect_obj::__register();
::EReg_obj::__register();
::haxe::zip::FlushMode_obj::__boot();
::haxe::io::Error_obj::__boot();
::haxe::io::Encoding_obj::__boot();
::format::png::Chunk_obj::__boot();
::format::png::Color_obj::__boot();
::haxe::Log_obj::__boot();
::Xml_obj::__boot();
::haxe::xml::Parser_obj::__boot();
::justPath::_CurveMath::CurveMath_Fields__obj::__boot();
::pixelimage::_Endian::Endian_Fields__obj::__boot();
}

