// Generated by Haxe 4.3.0-rc.1+
#ifndef INCLUDED_pixelimage_algo_IhitObj
#define INCLUDED_pixelimage_algo_IhitObj

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS2(pixelimage,algo,IhitObj)

namespace pixelimage{
namespace algo{


class HXCPP_CLASS_ATTRIBUTES IhitObj_obj {
	public:
		typedef ::hx::Object super;
		HX_DO_INTERFACE_RTTI;

};

} // end namespace pixelimage
} // end namespace algo

#endif /* INCLUDED_pixelimage_algo_IhitObj */ 
