// Generated by Haxe 4.3.0-rc.1+
#ifndef INCLUDED_pixelimage_samples_pixelimage_format__Grid_Grid_Fields_
#define INCLUDED_pixelimage_samples_pixelimage_format__Grid_Grid_Fields_

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS3(pixelimage_samples,pixelimage_format,_Grid,Grid_Fields_)

namespace pixelimage_samples{
namespace pixelimage_format{
namespace _Grid{


class HXCPP_CLASS_ATTRIBUTES Grid_Fields__obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef Grid_Fields__obj OBJ_;
		Grid_Fields__obj();

	public:
		enum { _hx_ClassId = 0x5c002514 };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="pixelimage_samples.pixelimage_format._Grid.Grid_Fields_")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,false,"pixelimage_samples.pixelimage_format._Grid.Grid_Fields_"); }

		inline static ::hx::ObjectPtr< Grid_Fields__obj > __new() {
			::hx::ObjectPtr< Grid_Fields__obj > __this = new Grid_Fields__obj();
			__this->__construct();
			return __this;
		}

		inline static ::hx::ObjectPtr< Grid_Fields__obj > __alloc(::hx::Ctx *_hx_ctx) {
			Grid_Fields__obj *__this = (Grid_Fields__obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(Grid_Fields__obj), false, "pixelimage_samples.pixelimage_format._Grid.Grid_Fields_"));
			*(void **)__this = Grid_Fields__obj::_hx_vtable;
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~Grid_Fields__obj();

		HX_DO_RTTI_ALL;
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("Grid_Fields_",0d,f6,32,e7); }

		static void main();
		static ::Dynamic main_dyn();

};

} // end namespace pixelimage_samples
} // end namespace pixelimage_format
} // end namespace _Grid

#endif /* INCLUDED_pixelimage_samples_pixelimage_format__Grid_Grid_Fields_ */ 
