// Generated by Haxe 4.3.0-rc.1+
#ifndef INCLUDED_pixelimage__Pixelimage_Pixelimage_Impl_
#define INCLUDED_pixelimage__Pixelimage_Pixelimage_Impl_

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS1(pixelimage,ImageStruct)
HX_DECLARE_CLASS2(pixelimage,_Pixelimage,Pixelimage_Impl_)

namespace pixelimage{
namespace _Pixelimage{


class HXCPP_CLASS_ATTRIBUTES Pixelimage_Impl__obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef Pixelimage_Impl__obj OBJ_;
		Pixelimage_Impl__obj();

	public:
		enum { _hx_ClassId = 0x42d3c4d0 };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="pixelimage._Pixelimage.Pixelimage_Impl_")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,false,"pixelimage._Pixelimage.Pixelimage_Impl_"); }

		inline static ::hx::ObjectPtr< Pixelimage_Impl__obj > __new() {
			::hx::ObjectPtr< Pixelimage_Impl__obj > __this = new Pixelimage_Impl__obj();
			__this->__construct();
			return __this;
		}

		inline static ::hx::ObjectPtr< Pixelimage_Impl__obj > __alloc(::hx::Ctx *_hx_ctx) {
			Pixelimage_Impl__obj *__this = (Pixelimage_Impl__obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(Pixelimage_Impl__obj), false, "pixelimage._Pixelimage.Pixelimage_Impl_"));
			*(void **)__this = Pixelimage_Impl__obj::_hx_vtable;
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~Pixelimage_Impl__obj();

		HX_DO_RTTI_ALL;
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("Pixelimage_Impl_",95,09,69,3d); }

		static ::pixelimage::ImageStruct scaleUpInt(::pixelimage::ImageStruct this1,::hx::Null< int >  scaleW,::hx::Null< int >  scaleH,::hx::Null< bool >  transparent,::hx::Null< bool >  includeMask);
		static ::Dynamic scaleUpInt_dyn();

};

} // end namespace pixelimage
} // end namespace _Pixelimage

#endif /* INCLUDED_pixelimage__Pixelimage_Pixelimage_Impl_ */ 
