// Generated by Haxe 4.3.0-rc.1+
#ifndef INCLUDED_justPath__CurveMath_CurveMath_Fields_
#define INCLUDED_justPath__CurveMath_CurveMath_Fields_

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS2(justPath,_CurveMath,CurveMath_Fields_)

namespace justPath{
namespace _CurveMath{


class HXCPP_CLASS_ATTRIBUTES CurveMath_Fields__obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef CurveMath_Fields__obj OBJ_;
		CurveMath_Fields__obj();

	public:
		enum { _hx_ClassId = 0x405c1971 };

		void __construct();
		inline void *operator new(size_t inSize, bool inContainer=false,const char *inName="justPath._CurveMath.CurveMath_Fields_")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,false,"justPath._CurveMath.CurveMath_Fields_"); }

		inline static ::hx::ObjectPtr< CurveMath_Fields__obj > __new() {
			::hx::ObjectPtr< CurveMath_Fields__obj > __this = new CurveMath_Fields__obj();
			__this->__construct();
			return __this;
		}

		inline static ::hx::ObjectPtr< CurveMath_Fields__obj > __alloc(::hx::Ctx *_hx_ctx) {
			CurveMath_Fields__obj *__this = (CurveMath_Fields__obj*)(::hx::Ctx::alloc(_hx_ctx, sizeof(CurveMath_Fields__obj), false, "justPath._CurveMath.CurveMath_Fields_"));
			*(void **)__this = CurveMath_Fields__obj::_hx_vtable;
			return __this;
		}

		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~CurveMath_Fields__obj();

		HX_DO_RTTI_ALL;
		static bool __GetStatic(const ::String &inString, Dynamic &outValue, ::hx::PropertyAccess inCallProp);
		static bool __SetStatic(const ::String &inString, Dynamic &ioValue, ::hx::PropertyAccess inCallProp);
		static void __register();
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("CurveMath_Fields_",1e,0a,99,59); }

		static void __boot();
		static Float quadStep;
};

} // end namespace justPath
} // end namespace _CurveMath

#endif /* INCLUDED_justPath__CurveMath_CurveMath_Fields_ */ 
