// Generated by Haxe 4.3.0-rc.1+
#include <hxcpp.h>

#ifndef INCLUDED_justPath_ILinePathContext
#include <justPath/ILinePathContext.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_contour_ArrowShape
#include <pixelimage/triangleGML/contour/ArrowShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_contour_CubicCurveShape
#include <pixelimage/triangleGML/contour/CubicCurveShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_contour_LineGridShape
#include <pixelimage/triangleGML/contour/LineGridShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_contour_LineShape
#include <pixelimage/triangleGML/contour/LineShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_contour_PolyLineShape
#include <pixelimage/triangleGML/contour/PolyLineShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_contour_QuadCurveShape
#include <pixelimage/triangleGML/contour/QuadCurveShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_contour_QuadShape
#include <pixelimage/triangleGML/contour/QuadShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_contour_QuadSoftShape
#include <pixelimage/triangleGML/contour/QuadSoftShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_contour_QuintShape
#include <pixelimage/triangleGML/contour/QuintShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_contour_SoftEllipseShape
#include <pixelimage/triangleGML/contour/SoftEllipseShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_contour_ThruCurveShape
#include <pixelimage/triangleGML/contour/ThruCurveShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_contour_TriangleSoftShape
#include <pixelimage/triangleGML/contour/TriangleSoftShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_coreShape_BasicGradient
#include <pixelimage/triangleGML/coreShape/BasicGradient.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_coreShape_BasicShape
#include <pixelimage/triangleGML/coreShape/BasicShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_coreShape_FillShape
#include <pixelimage/triangleGML/coreShape/FillShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_coreShape_GroupShape
#include <pixelimage/triangleGML/coreShape/GroupShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_coreShape_PatternShape
#include <pixelimage/triangleGML/coreShape/PatternShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_coreShape_PatternStroke
#include <pixelimage/triangleGML/coreShape/PatternStroke.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_coreShape_ShapeInterface
#include <pixelimage/triangleGML/coreShape/ShapeInterface.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_coreShape__TriangleGML_TriangleGML_Fields_
#include <pixelimage/triangleGML/coreShape/_TriangleGML/TriangleGML_Fields_.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_gradient_ArrowThickGradient
#include <pixelimage/triangleGML/gradient/ArrowThickGradient.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_gradient_EllipseRadialGradient
#include <pixelimage/triangleGML/gradient/EllipseRadialGradient.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_gradient_PathElementThickGradient
#include <pixelimage/triangleGML/gradient/PathElementThickGradient.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_gradient_QuadGradient
#include <pixelimage/triangleGML/gradient/QuadGradient.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_gradient_TriangleGradient
#include <pixelimage/triangleGML/gradient/TriangleGradient.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_gradientContour_LineGradient
#include <pixelimage/triangleGML/gradientContour/LineGradient.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_gradientContour_PolyLineGradient
#include <pixelimage/triangleGML/gradientContour/PolyLineGradient.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_patternContour_CubicCurvePattern
#include <pixelimage/triangleGML/patternContour/CubicCurvePattern.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_patternContour_LinePattern
#include <pixelimage/triangleGML/patternContour/LinePattern.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_patternContour_QuadPattern
#include <pixelimage/triangleGML/patternContour/QuadPattern.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_patternContour_TrianglePattern
#include <pixelimage/triangleGML/patternContour/TrianglePattern.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_patternShape_ArcPattern
#include <pixelimage/triangleGML/patternShape/ArcPattern.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_patternShape_CirclePattern
#include <pixelimage/triangleGML/patternShape/CirclePattern.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_patternShape_EllipsePattern
#include <pixelimage/triangleGML/patternShape/EllipsePattern.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_patternShape_PathElementPattern
#include <pixelimage/triangleGML/patternShape/PathElementPattern.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_patternShape_QuadrilateralPattern
#include <pixelimage/triangleGML/patternShape/QuadrilateralPattern.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_patternShape_RectanglePattern
#include <pixelimage/triangleGML/patternShape/RectanglePattern.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_patternShape_SquarePattern
#include <pixelimage/triangleGML/patternShape/SquarePattern.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_shape_ArcShape
#include <pixelimage/triangleGML/shape/ArcShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_shape_CircleShape
#include <pixelimage/triangleGML/shape/CircleShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_shape_EllipseShape
#include <pixelimage/triangleGML/shape/EllipseShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_shape_PathElementShape
#include <pixelimage/triangleGML/shape/PathElementShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_shape_QuadrilateralShape
#include <pixelimage/triangleGML/shape/QuadrilateralShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_shape_RectangleShape
#include <pixelimage/triangleGML/shape/RectangleShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_shape_SquareShape
#include <pixelimage/triangleGML/shape/SquareShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_shape_Star6Shape
#include <pixelimage/triangleGML/shape/Star6Shape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_shape_TriangleShape
#include <pixelimage/triangleGML/shape/TriangleShape.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_shape_VePathElementShape
#include <pixelimage/triangleGML/shape/VePathElementShape.h>
#endif

HX_LOCAL_STACK_FRAME(_hx_pos_20e608088cd0f0ee_115_getTriangleGML,"pixelimage.triangleGML.coreShape._TriangleGML.TriangleGML_Fields_","getTriangleGML",0x7ea88fcb,"pixelimage.triangleGML.coreShape._TriangleGML.TriangleGML_Fields_.getTriangleGML","pixelimage/triangleGML/coreShape/TriangleGML.hx",115,0xc65b1db8)
namespace pixelimage{
namespace triangleGML{
namespace coreShape{
namespace _TriangleGML{

void TriangleGML_Fields__obj::__construct() { }

Dynamic TriangleGML_Fields__obj::__CreateEmpty() { return new TriangleGML_Fields__obj; }

void *TriangleGML_Fields__obj::_hx_vtable = 0;

Dynamic TriangleGML_Fields__obj::__Create(::hx::DynamicArray inArgs)
{
	::hx::ObjectPtr< TriangleGML_Fields__obj > _hx_result = new TriangleGML_Fields__obj();
	_hx_result->__construct();
	return _hx_result;
}

bool TriangleGML_Fields__obj::_hx_isInstanceOf(int inClassId) {
	return inClassId==(int)0x00000001 || inClassId==(int)0x45c489ad;
}

::Dynamic TriangleGML_Fields__obj::getTriangleGML(::String nodeName){
            	HX_GC_STACKFRAME(&_hx_pos_20e608088cd0f0ee_115_getTriangleGML)
HXLINE( 116)		::String triangleGMLname = nodeName;
HXLINE( 117)		::Dynamic s;
HXDLIN( 117)		::String _hx_switch_0 = triangleGMLname;
            		if (  (_hx_switch_0==HX_("ArcPattern",3e,82,b3,bf)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::patternShape::ArcPattern_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("ArcShape",8f,e7,fc,ae)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::shape::ArcShape_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("ArrowShape",b8,c4,70,e6)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::contour::ArrowShape_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("ArrowThickGradient",04,6a,dd,c6)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::gradient::ArrowThickGradient_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("CirclePattern",00,6e,44,66)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::patternShape::CirclePattern_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("CircleShape",d1,fe,27,a3)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::shape::CircleShape_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("CubicCurvePattern",ab,55,8d,90)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::patternContour::CubicCurvePattern_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("CubicCurveShape",bc,15,cd,48)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::contour::CubicCurveShape_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("EllipsePattern",32,79,9e,d0)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::patternShape::EllipsePattern_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("EllipseRadialGradient",4d,b9,33,00)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::gradient::EllipseRadialGradient_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("EllipseShape",83,79,68,e0)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::shape::EllipseShape_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("LineGradient",24,6e,3d,3d)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::gradientContour::LineGradient_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("LineGridShape",c7,a7,4f,fc)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::contour::LineGridShape_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("LinePattern",9c,54,fd,33)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::patternContour::LinePattern_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("LineShape",6d,c6,ea,64)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::contour::LineShape_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("PathElementPattern",99,63,8f,25)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::patternShape::PathElementPattern_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("PathElementShape",2a,2c,8a,e3)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::shape::PathElementShape_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("PathElementThickGradient",76,93,b6,15)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::gradient::PathElementThickGradient_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("PathSoftElementPattern",a3,d0,8d,3a)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::patternShape::PathElementPattern_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("PolyLineGradient",90,0a,7f,2e)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::gradientContour::PolyLineGradient_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("PolyLineShape",81,6e,1a,f4)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::contour::PolyLineShape_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("QuadCurveShape",b9,db,be,8a)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::contour::QuadCurveShape_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("QuadGradient",f7,19,ae,f9)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::gradient::QuadGradient_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("QuadPattern",29,44,5e,cc)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::patternContour::QuadPattern_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("QuadShape",ba,c8,0c,af)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::contour::QuadShape_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("QuadSoftShape",f0,4b,24,43)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::contour::QuadSoftShape_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("QuadrilateralPattern",77,ed,d3,62)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::patternShape::QuadrilateralPattern_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("QuadrilateralShape",88,e2,ad,07)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::shape::QuadrilateralShape_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("QuintShape",b6,ee,7e,04)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::contour::QuintShape_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("RectanglePattern",01,aa,8b,8d)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::patternShape::RectanglePattern_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("RectangleShape",92,88,e8,31)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::shape::RectangleShape_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("SoftEllipseShape",8d,29,68,3a)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::contour::SoftEllipseShape_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("SquarePattern",13,7b,f6,c3)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::patternShape::SquarePattern_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("SquareShape",24,91,52,b3)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::shape::SquareShape_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("Star6Shape",7d,60,c4,c4)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::shape::Star6Shape_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("ThruCurveShape",29,dd,7b,34)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::contour::ThruCurveShape_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("TriangleGradient",f8,98,39,71)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::gradient::TriangleGradient_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("TrianglePattern",48,60,4b,44)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::patternContour::TrianglePattern_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("TriangleShape",19,4f,44,85)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::shape::TriangleShape_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("TriangleSoftShape",cf,ed,a7,65)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::contour::TriangleSoftShape_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		if (  (_hx_switch_0==HX_("VePathElementShape",79,45,4e,bb)) ){
HXLINE( 117)			s = ::pixelimage::triangleGML::shape::VePathElementShape_obj::__alloc( HX_CTX ,null(),null(),null(),null(),null(),null(),null(),null(),null(),null(),null());
HXDLIN( 117)			goto _hx_goto_0;
            		}
            		/* default */{
HXLINE( 206)			HX_STACK_DO_THROW(HX_("shape unfound",4a,a9,cc,60));
            		}
            		_hx_goto_0:;
HXLINE( 208)		return s;
            	}


STATIC_HX_DEFINE_DYNAMIC_FUNC1(TriangleGML_Fields__obj,getTriangleGML,return )


TriangleGML_Fields__obj::TriangleGML_Fields__obj()
{
}

bool TriangleGML_Fields__obj::__GetStatic(const ::String &inName, Dynamic &outValue, ::hx::PropertyAccess inCallProp)
{
	switch(inName.length) {
	case 14:
		if (HX_FIELD_EQ(inName,"getTriangleGML") ) { outValue = getTriangleGML_dyn(); return true; }
	}
	return false;
}

#ifdef HXCPP_SCRIPTABLE
static ::hx::StorageInfo *TriangleGML_Fields__obj_sMemberStorageInfo = 0;
static ::hx::StaticInfo *TriangleGML_Fields__obj_sStaticStorageInfo = 0;
#endif

::hx::Class TriangleGML_Fields__obj::__mClass;

static ::String TriangleGML_Fields__obj_sStaticFields[] = {
	HX_("getTriangleGML",a8,24,ec,3d),
	::String(null())
};

void TriangleGML_Fields__obj::__register()
{
	TriangleGML_Fields__obj _hx_dummy;
	TriangleGML_Fields__obj::_hx_vtable = *(void **)&_hx_dummy;
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("pixelimage.triangleGML.coreShape._TriangleGML.TriangleGML_Fields_",eb,29,06,6b);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mConstructEmpty = &__CreateEmpty;
	__mClass->mConstructArgs = &__Create;
	__mClass->mGetStaticField = &TriangleGML_Fields__obj::__GetStatic;
	__mClass->mSetStaticField = &::hx::Class_obj::SetNoStaticField;
	__mClass->mStatics = ::hx::Class_obj::dupFunctions(TriangleGML_Fields__obj_sStaticFields);
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(0 /* sMemberFields */);
	__mClass->mCanCast = ::hx::TCanCast< TriangleGML_Fields__obj >;
#ifdef HXCPP_SCRIPTABLE
	__mClass->mMemberStorageInfo = TriangleGML_Fields__obj_sMemberStorageInfo;
#endif
#ifdef HXCPP_SCRIPTABLE
	__mClass->mStaticStorageInfo = TriangleGML_Fields__obj_sStaticStorageInfo;
#endif
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace pixelimage
} // end namespace triangleGML
} // end namespace coreShape
} // end namespace _TriangleGML
