// Generated by Haxe 4.3.0-rc.1+
#ifndef INCLUDED_justPath_SvgLinePath
#define INCLUDED_justPath_SvgLinePath

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS1(justPath,ILinePathContext)
HX_DECLARE_CLASS1(justPath,StoreF6)
HX_DECLARE_CLASS1(justPath,SvgLinePath)

namespace justPath{


class HXCPP_CLASS_ATTRIBUTES SvgLinePath_obj : public ::hx::Object
{
	public:
		typedef ::hx::Object super;
		typedef SvgLinePath_obj OBJ_;
		SvgLinePath_obj();

	public:
		enum { _hx_ClassId = 0x1fbed828 };

		void __construct(::Dynamic pathContext_);
		inline void *operator new(size_t inSize, bool inContainer=true,const char *inName="justPath.SvgLinePath")
			{ return ::hx::Object::operator new(inSize,inContainer,inName); }
		inline void *operator new(size_t inSize, int extra)
			{ return ::hx::Object::operator new(inSize+extra,true,"justPath.SvgLinePath"); }
		static ::hx::ObjectPtr< SvgLinePath_obj > __new(::Dynamic pathContext_);
		static ::hx::ObjectPtr< SvgLinePath_obj > __alloc(::hx::Ctx *_hx_ctx,::Dynamic pathContext_);
		static void * _hx_vtable;
		static Dynamic __CreateEmpty();
		static Dynamic __Create(::hx::DynamicArray inArgs);
		//~SvgLinePath_obj();

		HX_DO_RTTI_ALL;
		::hx::Val __Field(const ::String &inString, ::hx::PropertyAccess inCallProp);
		::hx::Val __SetField(const ::String &inString,const ::hx::Val &inValue, ::hx::PropertyAccess inCallProp);
		void __GetFields(Array< ::String> &outFields);
		static void __register();
		void __Mark(HX_MARK_PARAMS);
		void __Visit(HX_VISIT_PARAMS);
		bool _hx_isInstanceOf(int inClassId);
		::String __ToString() const { return HX_("SvgLinePath",1d,36,be,aa); }

		::String str;
		int pos;
		Float lastX;
		Float lastY;
		Float controlX;
		Float controlY;
		int c;
		int l;
		Float px;
		Float py;
		::Dynamic pathContext;
		::justPath::StoreF6 store;
		::String parse(::String str_);
		::Dynamic parse_dyn();

};

} // end namespace justPath

#endif /* INCLUDED_justPath_SvgLinePath */ 
