// Generated by Haxe 4.3.0-rc.1+
#ifndef INCLUDED_pixelimage_triangleGML_coreShape_ShapeInterface
#define INCLUDED_pixelimage_triangleGML_coreShape_ShapeInterface

#ifndef HXCPP_H
#include <hxcpp.h>
#endif

HX_DECLARE_CLASS1(pixelimage,ImageStruct)
HX_DECLARE_CLASS3(pixelimage,triangleGML,coreShape,ShapeInterface)

namespace pixelimage{
namespace triangleGML{
namespace coreShape{


class HXCPP_CLASS_ATTRIBUTES ShapeInterface_obj {
	public:
		typedef ::hx::Object super;
		HX_DO_INTERFACE_RTTI;

		void (::hx::Object :: *_hx_setParameter)(::String name,::String value); 
		static inline void setParameter( ::Dynamic _hx_,::String name,::String value) {
			(_hx_.mPtr->*( ::hx::interface_cast< ::pixelimage::triangleGML::coreShape::ShapeInterface_obj *>(_hx_.mPtr->_hx_getInterface(0x99aa51b1)))->_hx_setParameter)(name,value);
		}
		void (::hx::Object :: *_hx_translate)(Float x,Float y); 
		static inline void translate( ::Dynamic _hx_,Float x,Float y) {
			(_hx_.mPtr->*( ::hx::interface_cast< ::pixelimage::triangleGML::coreShape::ShapeInterface_obj *>(_hx_.mPtr->_hx_getInterface(0x99aa51b1)))->_hx_translate)(x,y);
		}
		::pixelimage::ImageStruct (::hx::Object :: *_hx_render)(::pixelimage::ImageStruct pixelShape); 
		static inline ::pixelimage::ImageStruct render( ::Dynamic _hx_,::pixelimage::ImageStruct pixelShape) {
			return (_hx_.mPtr->*( ::hx::interface_cast< ::pixelimage::triangleGML::coreShape::ShapeInterface_obj *>(_hx_.mPtr->_hx_getInterface(0x99aa51b1)))->_hx_render)(pixelShape);
		}
};

} // end namespace pixelimage
} // end namespace triangleGML
} // end namespace coreShape

#endif /* INCLUDED_pixelimage_triangleGML_coreShape_ShapeInterface */ 
