// Generated by Haxe 4.3.0-rc.1+
#include <hxcpp.h>

#ifndef INCLUDED_justPath_ILinePathContext
#include <justPath/ILinePathContext.h>
#endif

namespace justPath{


static ::String ILinePathContext_obj_sMemberFields[] = {
	HX_("moveTo",ec,d2,ac,cc),
	HX_("lineTo",8f,46,a0,ec),
	HX_("lineSegmentTo",7a,d5,67,57),
	::String(null()) };

::hx::Class ILinePathContext_obj::__mClass;

void ILinePathContext_obj::__register()
{
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("justPath.ILinePathContext",0a,40,49,3f);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(ILinePathContext_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TIsInterface< (int)0x4fa789de >;
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace justPath
