// Generated by Haxe 4.3.0-rc.1+
#include <hxcpp.h>

#ifndef INCLUDED_pixelimage_ImageStruct
#include <pixelimage/ImageStruct.h>
#endif
#ifndef INCLUDED_pixelimage_triangleGML_coreShape_ShapeInterface
#include <pixelimage/triangleGML/coreShape/ShapeInterface.h>
#endif

namespace pixelimage{
namespace triangleGML{
namespace coreShape{


static ::String ShapeInterface_obj_sMemberFields[] = {
	HX_("setParameter",a7,f5,ff,6c),
	HX_("translate",4e,d7,7f,49),
	HX_("render",56,6b,29,05),
	::String(null()) };

::hx::Class ShapeInterface_obj::__mClass;

void ShapeInterface_obj::__register()
{
	::hx::Static(__mClass) = new ::hx::Class_obj();
	__mClass->mName = HX_("pixelimage.triangleGML.coreShape.ShapeInterface",ed,84,1b,56);
	__mClass->mSuper = &super::__SGetClass();
	__mClass->mMembers = ::hx::Class_obj::dupFunctions(ShapeInterface_obj_sMemberFields);
	__mClass->mCanCast = ::hx::TIsInterface< (int)0x99aa51b1 >;
	::hx::_hx_RegisterClass(__mClass->mName, __mClass);
}

} // end namespace pixelimage
} // end namespace triangleGML
} // end namespace coreShape
